2025-03-18 18:43:46,204 ERROR: Exception on /api/issues/ [POST] [in /home/gachuuri/Eco-Connect/venv/lib/python3.10/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/home/gachuuri/Eco-Connect/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/home/gachuuri/Eco-Connect/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
  File "/home/gachuuri/Eco-Connect/venv/lib/python3.10/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/home/gachuuri/Eco-Connect/venv/lib/python3.10/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/gachuuri/Eco-Connect/venv/lib/python3.10/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/gachuuri/Eco-Connect/venv/lib/python3.10/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/home/gachuuri/Eco-Connect/venv/lib/python3.10/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
  File "/home/gachuuri/Eco-Connect/venv/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/gachuuri/Eco-Connect/venv/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/gachuuri/Eco-Connect/venv/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1048, "Column 'user_id' cannot be null")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gachuuri/Eco-Connect/venv/lib/python3.10/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/gachuuri/Eco-Connect/venv/lib/python3.10/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/gachuuri/Eco-Connect/venv/lib/python3.10/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/gachuuri/Eco-Connect/venv/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/gachuuri/Eco-Connect/venv/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/gachuuri/Eco-Connect/app/routes/issues.py", line 20, in create_issue
    db.session.commit()
  File "/home/gachuuri/Eco-Connect/venv/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 599, in commit
    return self._proxied.commit()
  File "/home/gachuuri/Eco-Connect/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2032, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/gachuuri/Eco-Connect/venv/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/gachuuri/Eco-Connect/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/gachuuri/Eco-Connect/venv/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/gachuuri/Eco-Connect/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/home/gachuuri/Eco-Connect/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4353, in flush
    self._flush(objects)
  File "/home/gachuuri/Eco-Connect/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4488, in _flush
    with util.safe_reraise():
  File "/home/gachuuri/Eco-Connect/venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/gachuuri/Eco-Connect/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4449, in _flush
    flush_context.execute()
  File "/home/gachuuri/Eco-Connect/venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/gachuuri/Eco-Connect/venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/gachuuri/Eco-Connect/venv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/gachuuri/Eco-Connect/venv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
  File "/home/gachuuri/Eco-Connect/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1416, in execute
    return meth(
  File "/home/gachuuri/Eco-Connect/venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/gachuuri/Eco-Connect/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/gachuuri/Eco-Connect/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1843, in _execute_context
    return self._exec_single_context(
  File "/home/gachuuri/Eco-Connect/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/gachuuri/Eco-Connect/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2352, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/gachuuri/Eco-Connect/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/home/gachuuri/Eco-Connect/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
  File "/home/gachuuri/Eco-Connect/venv/lib/python3.10/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/home/gachuuri/Eco-Connect/venv/lib/python3.10/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/gachuuri/Eco-Connect/venv/lib/python3.10/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/gachuuri/Eco-Connect/venv/lib/python3.10/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/home/gachuuri/Eco-Connect/venv/lib/python3.10/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
  File "/home/gachuuri/Eco-Connect/venv/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/gachuuri/Eco-Connect/venv/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/gachuuri/Eco-Connect/venv/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.IntegrityError: (pymysql.err.IntegrityError) (1048, "Column 'user_id' cannot be null")
[SQL: INSERT INTO issue (title, description, location, user_id, created_at) VALUES (%(title)s, %(description)s, %(location)s, %(user_id)s, %(created_at)s)]
[parameters: {'title': 'Illegal dumping', 'description': 'Over the last days it has been the residents of Kaniku trying to fight for our life. The area is o stinky. A lot of gabbage has been dumped near our residentials.', 'location': 'Eldoret', 'user_id': None, 'created_at': datetime.datetime(2025, 3, 18, 15, 43, 46, 201965)}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-03-18 18:43:46,205 CRITICAL: 500 Internal Server Error at http://127.0.0.1:5000/api/issues/ - Error: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application. [in /home/gachuuri/Eco-Connect/app/__init__.py:93]
2025-03-18 18:43:54,391 ERROR: 404 Error: http://127.0.0.1:5000/index.html [in /home/gachuuri/Eco-Connect/app/__init__.py:88]
2025-03-18 18:44:09,177 ERROR: 404 Error: http://127.0.0.1:5000/login.html [in /home/gachuuri/Eco-Connect/app/__init__.py:88]
2025-03-18 18:45:18,898 ERROR: 404 Error: http://127.0.0.1:5000/login.html [in /home/gachuuri/Eco-Connect/app/__init__.py:88]
2025-03-18 18:47:30,917 ERROR: 404 Error: http://127.0.0.1:5000/register.html [in /home/gachuuri/Eco-Connect/app/__init__.py:88]
2025-03-20 22:38:53,161 ERROR: 404 Error: http://127.0.0.1:5000/favicon.ico [in /home/gachuuri/Eco-Connect/app/__init__.py:88]
